-- Colorscheme
-- base16-gruvbox-dark-pale
-- base16-default-dark
-- base16-gruvbox-dark-hard
-- base16-harmonic-dark
-- base16-material-darker
-- vim.cmd('colorscheme base16-gruvbox-dark-hard')
-- vim.cmd('colorscheme base16-ayu-dark')
-- vim.cmd('colorscheme base16-nord')

-- Colorscheme is set by the theme plugin (see `lua/plugins/ui.lua`).
-- Put highlight overrides here if you want to tweak specific groups after the scheme loads.
