# tabspaces = 4

[shell]
program = "/opt/homebrew/bin/fish"

[font]
size = 13.0

[font.normal]
family = "BitstromWera Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Alt"
